apiVersion: batch/v1
kind: CronJob
metadata:
  name: dolar-webhook
spec:
  # UTC-0
  schedule: "0 13-18 * * 1-5" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dolar-webhook
            image: quay.io/agustinlare/dolar-wh
            env:
            - name: ENDPOINT_URL
              value: "https://www.dolarito.ar/api/frontend/quotations"
            - name: WEBHOOK_URL
              value: ""
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          
